### ISSUE TITLE
Feature request: char auto ord

### ISSUE THREAD

**Issue by coddra** [darrenks/atlas#3]
If you have time, please implement auto ord for chars on operators, that accept numbers but not chars.

What I mean:
```
'c%5
> 4
'd-3
> 97
```

Thanks in advance!

*May I create a pull request?*

**Comment by darrenks** [comment]
Hi coddra,

This would be good for code golf but it intentionally doesn't do this. The reason is that we pretend that we don't know the starting position of characters, only their relative positions, so operations like 'a+1 make sense because we know that is 'b without knowing the ascii value of 'a is 97. The BQN language calls this affine which is where I got the idea.

I like the affine thing because then there are no tricky cases like what should the type of Int-Char be or other combinations that don't have clear answers. It also opens up the possibility for overloading, like / meaning split (more overloading is possible for Char types and may be done in future).

**Comment by coddra** [comment]
Thanks for the explanation, it makes sense.
